services:
  - type: web
    name: beatsync-server
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health

  - type: web
    name: beatsync-client
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.client
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: beatsync-server
          type: web
          envVarKey: RENDER_EXTERNAL_URL
